### ISSUE TITLE
How do I get the navigation and the header to line up nicely?

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/modularity-mindfulness#2]
@mackenzierose

Sorry for the confusion! I'm just struggling as to how I can get the navigation to be placed on the right side of the banner. I tried align-items, justify-content, align-content. I'm not sure as to what went wrong.
<img width="565" alt="Screen Shot 2020-09-21 at 6 03 41 PM" src="https://user-images.githubusercontent.com/54897840/93826259-db8a6300-fc34-11ea-9800-22e3d8b0daa6.png">

**Comment by MacKenzieRose** [comment]
Hey!

So you have a bunch of unclosed/incomplete syntax in the CSS, which may cause some rendering issues.

But, one way to get the navigation over to the right might be to target the navigation directly, like this:
 `nav {`
`    display: flex;`
`    justify-content: flex-end;`
 ` }`

But make sure everything is closed first etc. so that way everything renders properly.

Let me know how it goes! 🙂

**Comment by Sophia-Villamayor** [comment]
@MacKenzieRose Thank you! I think I fixed the errors in my CSS. As for the nav, it doesn't seem to change. So sorry to bother!!

**Comment by MacKenzieRose** [comment]
Not a problem; let's try enabling flexbox for your whole header, by adding `display: flex;` to its CSS. This should make the navigation sit on the same line as your `div`. Then, let's `justify-content: space-between;` to send the navigation to the right side of the screen.

Let me know if that helps get you started 😸

**Comment by Sophia-Villamayor** [comment]
@MacKenzieRose Perfect! Thank you so much!!!
